-- =========================================================
-- V12: Mở rộng ngân hàng bài tập ngữ pháp (Phase 4)
--
-- Mục tiêu: mỗi điểm ngữ pháp đạt >= 5 câu (V9 mới có 2 câu/điểm).
-- Nhóm bẫy thường gặp (trợ từ は/が/へ/を/で, số đếm biến âm, tính từ い/な, so sánh, thể て) được gắn
-- is_common_mistake = TRUE để Trạm Trợ từ lọc riêng được nhiều câu hơn.
--
-- ⚠️ Nội dung là DRAFT do người soạn tự viết (không copy nguồn) — CHỜ giáo viên tiếng Nhật review trước khi chốt.
-- Idempotent: unique index (grammar_rule_id, question_text) từ V9 + ON CONFLICT DO NOTHING.
-- Lưu ý khi sửa: không dùng dấu ; trong chuỗi, không để dấu phẩy thừa cuối VALUES.
-- =========================================================

INSERT INTO grammar_exercises (grammar_rule_id, question_text, options_json, correct_answer, explanation, is_common_mistake, mistake_category)
SELECT r.id, e.question_text, e.options_json, e.correct_answer, e.explanation, e.is_common_mistake, e.mistake_category
FROM (VALUES
    -- ===== JPD113 — Bài 1 =====
    ('N1 は N2 です', 'サッカー __ スポーツ です。', '["は","が","を","と"]', 'は',
     'サッカー là chủ đề của câu nên dùng は (khi làm trợ từ は đọc là “wa”, không đọc “ha”).', TRUE, 'particle-ha'),
    ('N1 は N2 です', 'A: おなまえ は? B: わたし __ グエン です。', '["は","も","を","で"]', 'は',
     'Giới thiệu tên: わたし は N です — は đứng sau chủ thể được nói tới.', FALSE, NULL),
    ('N1 は N2 です', 'きょう は 日曜日 です。 あした __ 月曜日 です。', '["は","が","に","へ"]', 'は',
     'Mỗi câu có chủ đề riêng và đều đánh dấu bằng は.', FALSE, NULL),
    ('N1 は N2 じゃありません', 'A: たなかさん は せんせいですか。 B: いいえ、せんせい __ ありません。', '["では","です","ます","を"]', 'では',
     'Phủ định lịch sự đầy đủ: ではありません (khẩu ngữ: じゃありません).', FALSE, NULL),
    ('N1 は N2 じゃありません', 'A: それは あなた の かばんですか。 B: いいえ、わたし の かばん __。', '["じゃありません","です","ですか","でした"]', 'じゃありません',
     'Trả lời phủ định cho danh từ: いいえ、かばん じゃありません.', TRUE, 'polite-negative'),
    ('N1 は N2 じゃありません', 'わたし は にほんじん __ ありません。 ベトナムじん です。', '["では","です","じゃない","を"]', 'では',
     'Câu đầu phủ định bằng ではありません, câu sau khẳng định lại bằng です.', FALSE, NULL),
    ('N1 は N2 ですか', 'A: あの 人 は せんせいですか。 B: いいえ、__。', '["ちがいます","そうです","ですか","ではありません"]', 'ちがいます',
     'Trả lời phủ định gọn cho ですか: いいえ、ちがいます.', TRUE, 'polite-negative'),
    ('N1 は N2 ですか', 'あの 人 は だれ __。', '["ですか","ますか","でした","です"]', 'ですか',
     'Nghi vấn từ (だれ / なに / どこ) + ですか tạo câu hỏi lịch sự.', FALSE, NULL),
    ('N1 は N2 ですか', 'こちら は リンさん __。', '["ですか","です","でしたか","ますか"]', 'ですか',
     'Hỏi xác nhận người: N は N ですか.', FALSE, NULL),
    ('N も', 'わたし の 父 は せんせい です。 母 __ せんせい です。', '["も","は","が","の"]', 'も',
     'Cùng thuộc tính với người đã nhắc trước → も thay cho は.', FALSE, NULL),
    ('N も', 'A: わたし は がくせい です。 B: たなかさん __ がくせいですか。', '["も","は","を","に"]', 'も',
     'Hỏi “ai đó cũng vậy?” cũng dùng も: たなかさん も がくせいですか.', FALSE, NULL),
    ('N も', 'こちら は コーヒー です。 そちら __ コーヒー です。', '["も","は","が","で"]', 'も',
     'Nhấn “cũng là”: そちら も コーヒー です (も thay thế は).', TRUE, 'particle-ha'),
    -- ===== JPD113 — Bài 2 =====
    ('N1 の N2', 'これ は にほん __ くるま です。', '["の","は","を","に"]', 'の',
     'の chỉ xuất xứ / sở hữu: にほん の くるま = xe của Nhật.', FALSE, NULL),
    ('N1 の N2', 'リンさん は わたし __ ともだち です。', '["の","は","が","と"]', 'の',
     'N1 の N2: N2 thuộc N1 (bạn của tôi).', FALSE, NULL),
    ('N1 の N2', 'これは だれ __ かばん ですか。', '["の","は","が","を"]', 'の',
     'Hỏi sở hữu: だれ の N ですか.', FALSE, NULL),
    ('これ / それ / あれ は N です', '(vật ở gần người nghe) __ は なんですか。', '["それ","これ","あれ","この"]', 'それ',
     'それ = vật gần người nghe (xa người nói). これ gần người nói, あれ xa cả hai.', TRUE, 'demonstrative'),
    ('これ / それ / あれ は N です', '__ かばん は わたし の です。', '["この","これ","ここ","こちら"]', 'この',
     'この phải đi kèm danh từ (この かばん), còn これ đứng một mình không có danh từ theo sau.', TRUE, 'demonstrative'),
    ('これ / それ / あれ は N です', 'A: それは 何ですか。 B: __ は じしょ です。', '["これ","それ","あれ","どれ"]', 'これ',
     'Người trả lời cầm vật ở gần mình → đổi それ (phía người hỏi) thành これ.', TRUE, 'demonstrative'),
    ('N は どこですか', 'えき は __ ですか。', '["どこ","どれ","だれ","いくら"]', 'どこ',
     'どこ hỏi vị trí cho cả vật và người (lịch sự hơn dùng どちら khi hỏi người / nơi trang trọng).', FALSE, NULL),
    ('N は どこですか', 'A: ぎんこう は どこですか。 B: えき の となり __。', '["です","ます","ですか","でした"]', 'です',
     'Trả lời vị trí bằng mẫu <nơi> です.', FALSE, NULL),
    ('N は どこですか', 'A: トイレ は どこですか。 B: あそこ __。', '["です","に あります","ですか","でした"]', 'です',
     'Chỉ vị trí ngắn gọn: あそこ です.', FALSE, NULL),
    ('N が あります / います', 'へや に テレビ __ あります。', '["が","は","を","で"]', 'が',
     'Câu tồn tại: <nơi> に <vật> が あります — chủ thể tồn tại luôn đánh dấu bằng が.', TRUE, 'particle-ga'),
    ('N が あります / います', 'にわ に いぬ __ います。', '["が","は","を","へ"]', 'が',
     'Người / động vật dùng います + が: にわ に いぬ が います.', TRUE, 'particle-ga'),
    ('N が あります / います', 'A: へや に なに __ ありますか。 B: つくえ が あります。', '["が","は","を","も"]', 'が',
     'Câu hỏi tồn tại cũng dùng が: なに が ありますか (không dùng は).', FALSE, NULL),
    ('Vị trí tương đối: 上 / 下 / 前 / 後ろ / 隣 / 中', 'かばん は いす __ 上 に あります。', '["の","に","は","が"]', 'の',
     'N1 の 上 に N2 が あります — の nối vật mốc với từ chỉ vị trí.', FALSE, NULL),
    ('Vị trí tương đối: 上 / 下 / 前 / 後ろ / 隣 / 中', 'ぎんこう は えき __ 前 に あります。', '["の","で","に","を"]', 'の',
     'えき の 前 = phía trước nhà ga.', FALSE, NULL),
    ('Vị trí tương đối: 上 / 下 / 前 / 後ろ / 隣 / 中', 'いぬ は テーブル __ 下 に います。', '["の","が","を","へ"]', 'の',
     'Vật sống dùng います, nhưng vẫn là cấu trúc N1 の <vị trí> に N2 が います.', TRUE, 'position'),
    ('N は N の 中 です', 'さいふ は かばん __ 中 です。', '["の","に","は","が"]', 'の',
     'N1 は N2 の 中 です = N1 ở trong N2.', FALSE, NULL),
    ('N は N の 中 です', 'A: コーヒー は どこですか。 B: れいぞうこ __ 中 です。', '["の","に","へ","を"]', 'の',
     'Vật ở trong tủ lạnh: れいぞうこ の 中 です.', FALSE, NULL),
    ('N は N の 中 です', 'A: ぎんこう は どこですか。 B: えき の __ です。', '["中","上","となり","前"]', '中',
     'Trả lời “ở trong khu vực đó” bằng N の 中 です.', FALSE, NULL),
    ('いくらですか', 'A: この かさ は いくらですか。 B: せんえん __。', '["です","ます","ですか","でした"]', 'です',
     'Trả lời giá: <số tiền> です.', FALSE, NULL),
    ('いくらですか', 'この とけい は __ ですか。', '["いくら","いつ","だれ","どこ"]', 'いくら',
     'いくら là nghi vấn từ hỏi giá tiền.', FALSE, NULL),
    ('いくらですか', '(giá 1500 yên) せんごひゃく __ です。', '["円","人","台","本"]', '円',
     'Đơn vị tiền là 円 (えん): せんごひゃくえん = 1500 yên.', TRUE, 'counter-money'),
    ('N を ください', 'おみず __ ください。', '["を","が","に","へ"]', 'を',
     'N を ください: を đánh dấu vật được yêu cầu (đọc là “o”).', TRUE, 'particle-wo'),
    ('N を ください', 'A: いらっしゃいませ。 B: その りんご __ ください。', '["を","は","で","と"]', 'を',
     'Mua vật cụ thể: その N を ください.', TRUE, 'particle-wo'),
    ('N を ください', 'すみません、メニュー __ ください。', '["を","に","が","も"]', 'を',
     'Yêu cầu lịch sự khi gọi món: メニュー を ください.', FALSE, NULL),
    ('Giờ và phút: ～時 ～分', '9時 = ?', '["くじ","きゅうじ","ここのじ","くうじ"]', 'くじ',
     'Nhóm biến âm giờ: 4時 = よじ, 7時 = しちじ, 9時 = くじ (không đọc きゅうじ).', TRUE, 'counter-time'),
    ('Giờ và phút: ～時 ～分', '4時30分 = ?', '["よじさんじゅっぷん","よんじさんじゅっぷん","しじさんじゅうふん","よじさんじゅうふん"]', 'よじさんじゅっぷん',
     '4時 = よじ và 30分 = さんじゅっぷん (ふん biến âm thành ぷん).', TRUE, 'counter-time'),
    ('Giờ và phút: ～時 ～分', 'A: いま なんじですか。 B: __ です。', '["3時","3時間","3日","3分"]', '3時',
     'なんじ hỏi “mấy giờ” nên trả lời bằng ～時 (3時間 là “3 tiếng”, 3日 là “ngày 3”).', FALSE, NULL),
    ('Ngày tháng và thứ: ～月 ～日 ・～曜日', '4日 = ?', '["よっか","よんにち","しにち","よんか"]', 'よっか',
     'Biến âm ngày: 4日 = よっか, 8日 = ようか, 14日 = じゅうよっか.', TRUE, 'counter-date'),
    ('Ngày tháng và thứ: ～月 ～日 ・～曜日', '1日 = ?', '["ついたち","いちにち","いちか","ついか"]', 'ついたち',
     'Ngày 1 trong tháng đọc là ついたち (いちにち nghĩa là “một ngày”).', TRUE, 'counter-date'),
    ('Ngày tháng và thứ: ～月 ～日 ・～曜日', 'きょう は __ です。(hôm nay là thứ Ba)', '["火曜日","水曜日","木曜日","月曜日"]', '火曜日',
     'Thứ trong tuần: 月 ・ 火 ・ 水 ・ 木 ・ 金 ・ 土 ・ 日 + 曜日.', FALSE, NULL),
    ('Chia động từ: V ます / V ません', 'あした 図書館 へ __。', '["行きます","行きません","行きました","行く"]', '行きます',
     'Thời điểm tương lai (あした) + thể lịch sự khẳng định: 行きます.', FALSE, NULL),
    ('Chia động từ: V ます / V ません', 'A: まいにち テレビ を 見ますか。 B: いいえ、__。', '["見ません","見ます","見ました","見る"]', '見ません',
     'Phủ định lịch sự của 見ます là 見ません.', FALSE, NULL),
    ('Chia động từ: V ます / V ません', 'わたし は おさけ を __。(phủ định lịch sự của 飲みます)', '["飲みません","飲みます","飲みました","飲んで"]', '飲みません',
     'Động từ nhóm 1 đuôi み: 飲みます → 飲みません.', TRUE, 'verb-masu'),
    ('N へ 行きます', 'らいげつ 大阪 __ 行きます。', '["へ","を","で","と"]', 'へ',
     'へ (làm trợ từ đọc là “e”) chỉ hướng / đích đến, tương đương に.', TRUE, 'particle-he'),
    ('N へ 行きます', 'A: どこ __ 行きますか。 B: 会社へ 行きます。', '["へ","を","が","も"]', 'へ',
     'Hỏi đích đến: どこ へ 行きますか.', TRUE, 'particle-he'),
    ('N へ 行きます', 'A: あした 学校へ 行きますか。 B: いいえ、学校へ __。', '["行きません","行きます","行きました","行く"]', '行きません',
     'Trả lời phủ định: いいえ、～ へ 行きません.', FALSE, NULL),
    ('N で 行きます', '地下鉄 __ 会社へ 行きます。', '["で","に","へ","を"]', 'で',
     'で đánh dấu phương tiện di chuyển: バス で 行きます.', FALSE, NULL),
    ('N で 行きます', 'A: 何 __ 会社へ 行きますか。 B: 自転車で 行きます。', '["で","に","へ","と"]', 'で',
     'Hỏi phương tiện: 何 で 行きますか.', TRUE, 'transport'),
    ('N で 行きます', '(đi bộ tới ga) 駅まで __ 行きます。', '["あるいて","で","に","へ"]', 'あるいて',
     'Đi bộ KHÔNG dùng で mà dùng あるいて 行きます.', TRUE, 'transport'),
    ('Tính từ đuôi い và な', 'ゆうめい __ 人 です。', '["な","い","の","で"]', 'な',
     'ゆうめい là tính từ nhóm な nên phải thêm な khi bổ nghĩa danh từ.', TRUE, 'adjective-na'),
    ('Tính từ đuôi い và な', 'おいしい __ ラーメン です。', '["い","な","の","に"]', 'い',
     'おいしい thuộc nhóm い, giữ nguyên い khi đứng trước danh từ.', FALSE, NULL),
    ('Tính từ đuôi い và な', 'ふじさん は __ 山 です。', '["たかい","たかく","たかくて","たかの"]', 'たかい',
     'Tính từ い đứng trước danh từ giữ nguyên dạng: たかい 山.', TRUE, 'adjective-i'),
    ('Phủ định tính từ い', 'ふるい → phủ định:', '["ふるくないです","ふるいじゃないです","ふるではありません","ふるくありませんです"]', 'ふるくないです',
     'Tính từ い: bỏ い rồi thêm くないです.', TRUE, 'adjective-i'),
    ('Phủ định tính từ い', 'たかい → quá khứ phủ định:', '["たかくなかったです","たかくないでした","たかかったくないです","たかじゃなかったです"]', 'たかくなかったです',
     'Quá khứ phủ định của tính từ い: たかい → たかくなかったです.', TRUE, 'adjective-i'),
    ('Phủ định tính từ い', 'この 本 は __ です。(phủ định của おもしろい)', '["おもしろくない","おもしろいない","おもしろくなく","おもしろじゃない"]', 'おもしろくない',
     'Bỏ い rồi thêm くない, sau đó mới + です: おもしろくない です.', FALSE, NULL),
    ('Phủ định tính từ な', 'ゆうめい → phủ định:', '["ゆうめいじゃないです","ゆうめいくないです","ゆうめいないです","ゆうめくないです"]', 'ゆうめいじゃないです',
     'Tính từ な giữ nguyên rồi thêm じゃないです (không biến thành く).', TRUE, 'adjective-na'),
    ('Phủ định tính từ な', 'この 町 は __ です。(phủ định của にぎやか)', '["にぎやかじゃない","にぎやくない","にぎやかない","にぎやかくない"]', 'にぎやかじゃない',
     'にぎやか là tính từ な → にぎやか じゃない です.', TRUE, 'adjective-na'),
    ('Phủ định tính từ な', 'A: あの 人 は ハンサムですか。 B: いいえ、ハンサム __ です。', '["じゃない","くない","ない","くありません"]', 'じゃない',
     'Phủ định tính từ な: ハンサム じゃない です.', FALSE, NULL),
    ('N が ほしいです', 'こども の とき、ロボット __ ほしい でした。', '["が","を","は","に"]', 'が',
     'Quá khứ mong muốn: ほしい でした; đối tượng mong muốn vẫn đánh dấu bằng が.', FALSE, NULL),
    ('N が ほしいです', 'わたし は あたらしい かばん が __ です。', '["ほしい","たい","ほしく","ほしいだ"]', 'ほしい',
     'N が ほしいです = muốn có N. (たい dùng cho động từ, không dùng cho danh từ.)', TRUE, 'desire-hoshii'),
    ('N が ほしいです', 'Phủ định của ほしいです:', '["ほしくないです","ほしいじゃないです","ほしくありませんです","ほしないです"]', 'ほしくないです',
     'ほしい chia như tính từ い: ほしくないです.', TRUE, 'desire-hoshii'),
    ('V たいです', 'いつか 日本へ __ です。', '["行きたい","行くたい","行たい","行きますたい"]', '行きたい',
     'V-たい: bỏ ます của 行きます → 行き + たいです.', FALSE, NULL),
    ('V たいです', '今日 は 何 も __ です。(phủ định của 食べたい)', '["食べたくない","食べたいじゃない","食べないたい","食べたくありませんです"]', '食べたくない',
     'V-たい phủ định như tính từ い: 食べたくない です.', TRUE, 'verb-tai'),
    ('V たいです', 'A: 何 を __ ですか。 B: すし を 食べたいです。', '["食べたい","食べる","食べます","食べた"]', '食べたい',
     'Hỏi mong muốn: 何 を V-たい ですか.', FALSE, NULL),
    ('Mục đích chuyến đi: V に 行きます', '図書館へ 本を __ 行きます。', '["借りに","借りて","借りる","借りたい"]', '借りに',
     'Mục đích: V(ます形 bỏ ます) + に 行きます → 借りに 行きます.', FALSE, NULL),
    ('Mục đích chuyến đi: V に 行きます', '北海道へ スキーを __ 行きます。', '["しに","して","する","したい"]', 'しに',
     'します → し + に: スキー を しに 行きます.', FALSE, NULL),
    ('Mục đích chuyến đi: V に 行きます', 'Câu nào đúng để nói “tôi đi Nhật để học tiếng Nhật”?', '["日本へ 日本語を 勉強しに 行きます","日本へ 日本語を 勉強する に 行きます","日本へ 日本語を 勉強して 行きます","日本へ 日本語を 勉強します に 行きます"]', '日本へ 日本語を 勉強しに 行きます',
     'Động từ nhóm 3 (勉強します) → 勉強し に 行きます (bỏ ます rồi thêm に).', TRUE, 'purpose-ni'),
    ('N と V ます (làm cùng ai)', 'かのじょ __ 映画を 見ます。', '["と","を","に","で"]', 'と',
     'と đánh dấu người cùng thực hiện hành động.', FALSE, NULL),
    ('N と V ます (làm cùng ai)', '家族 __ ごはんを 食べます。', '["と","で","に","へ"]', 'と',
     'Cùng làm với gia đình → dùng と.', FALSE, NULL),
    ('N と V ます (làm cùng ai)', 'A: だれ __ 日本へ 行きますか。 B: 友達と 行きます。', '["と","を","に","へ"]', 'と',
     'Hỏi người cùng đi: だれ と 行きますか.', TRUE, 'particle-to'),
    ('Thời gian: いつ / ～から ～まで', '__ 日本へ 行きますか。 3月に 行きます。', '["いつ","なんじ","どこ","だれ"]', 'いつ',
     'いつ hỏi thời điểm chung; khi trả lời cụ thể thường thêm に (3月 に 行きます).', FALSE, NULL),
    ('Thời gian: いつ / ～から ～まで', '月曜日 __ 金曜日まで 学校へ 行きます。', '["から","まで","に","ごろ"]', 'から',
     'Cặp ～から ～まで: bắt đầu bằng から, kết thúc bằng まで.', TRUE, 'time-range'),
    ('Thời gian: いつ / ～から ～まで', 'A: まいにち 何時から 働きますか。 B: 9時 __ 働きます。', '["から","まで","に","で"]', 'から',
     'Trả lời tương ứng với から: 9時 から 働きます.', FALSE, NULL),
    ('So sánh hơn: A と B と どちらが', 'A: コーヒー と お茶 と __ が 好きですか。', '["どちら","どれ","なに","だれ"]', 'どちら',
     'So sánh hai đối tượng dùng どちら (どれ dùng cho từ 3 đối tượng trở lên).', FALSE, NULL),
    ('So sánh hơn: A と B と どちらが', 'コーヒー の __ が 好きです。', '["ほう","より","まで","から"]', 'ほう',
     'A の ほうが B より ～です = A thì hơn B.', FALSE, NULL),
    ('So sánh hơn: A と B と どちらが', 'A: 日本語 と 英語 と どちらが 難しいですか。 B: 日本語 の ほうが 英語 __ 難しいです。', '["より","ほう","まで","ほど"]', 'より',
     'より đứng sau đối tượng bị so sánh: 英語 より 難しいです.', TRUE, 'comparison'),
    ('So sánh nhất: 一番', 'クラス __ 一番 背が 高い 人 は たなかさん です。', '["で","に","を","の"]', 'で',
     'Phạm vi so sánh dùng で: クラス で 一番 ～.', TRUE, 'comparison'),
    ('So sánh nhất: 一番', '一年 __ 中 で 8月 が 一番 暑いです。', '["の","で","に","は"]', 'の',
     '一年 の 中 で = trong cả một năm (phạm vi để so sánh).', TRUE, 'comparison'),
    ('So sánh nhất: 一番', '日本の 食べ物 __ 何 が 一番 好きですか。', '["で","に","を","と"]', 'で',
     'Phạm vi lựa chọn cũng dùng で: 食べ物 で 何 が 一番 好きですか.', FALSE, NULL),
    ('Quá khứ tính từ い', 'きのう の パーティー は __ です。', '["楽しかった","楽しいかった","楽しでした","楽しいでした"]', '楽しかった',
     'Tính từ い ở quá khứ: bỏ い + かったです → 楽しかったです.', TRUE, 'adjective-i'),
    ('Quá khứ tính từ い', 'きのう の しけん は __ です。(phủ định quá khứ của 難しい)', '["難しくなかった","難しくないでした","難しいじゃなかった","難しいくなかった"]', '難しくなかった',
     'Phủ định quá khứ của tính từ い: 難しい → 難しくなかったです.', TRUE, 'adjective-i'),
    ('Quá khứ tính từ い', 'A: きのう の 天気 は よかったですか。 B: いいえ、__。', '["よくなかったです","よくないでした","いいじゃなかったです","よいくなかったです"]', 'よくなかったです',
     'Ngoại lệ: いい → よかった → よくなかった です.', TRUE, 'adjective-i'),
    ('Động từ thể て', 'Thể て của 食べます:', '["食べて","食べって","食べきて","食べるて"]', '食べて',
     'Động từ nhóm 2: bỏ ます rồi thêm て → 食べて.', FALSE, NULL),
    ('Động từ thể て', 'Thể て của 書きます:', '["書いて","書きて","書くて","書んで"]', '書いて',
     'Đuôi き (nhóm 1) → いて: 書く → 書いて. Riêng 行く là ngoại lệ: 行く → 行って.', TRUE, 'te-form'),
    ('Động từ thể て', 'Thể て của 飲みます:', '["飲んで","飲みて","飲いて","飲て"]', '飲んで',
     'Đuôi み / び / ぬ (nhóm 1) → んで: 飲む → 飲んで.', TRUE, 'te-form'),
    ('Xin phép: V てもいいですか', 'まど を 開け __ いいですか。', '["ても","ては","で","た"]', 'ても',
     'Xin phép: V-て も いいですか.', FALSE, NULL),
    ('Xin phép: V てもいいですか', 'A: ここに 車を とめても いいですか。 B: すみません、__。', '["ここは とめては いけません","どうぞ","はい、いいですよ","もちろんです"]', 'ここは とめては いけません',
     'Nếu không được phép thì dùng ては いけません (không trả lời いいですよ).', TRUE, 'te-form'),
    ('Xin phép: V てもいいですか', 'Ý nghĩa của V てもいいですか:', '["Xin phép làm gì đó","Nhờ ai đừng làm gì đó","Bắt buộc phải làm gì đó","Đã làm gì đó rồi"]', 'Xin phép làm gì đó',
     'V-てもいいですか là mẫu xin phép, trả lời はい、いいですよ / どうぞ.', FALSE, NULL),
    ('Cấm đoán: V てはいけません', 'ここに 車を とめ __ いけません。', '["ては","ても","て","では"]', 'ては',
     'Cấm đoán: V-て は いけません.', TRUE, 'te-form'),
    ('Cấm đoán: V てはいけません', 'A: ここで タバコを 吸っても いいですか。 B: いいえ、__。', '["吸っては いけません","吸っても いいです","吸わないで くださいません","吸います"]', '吸っては いけません',
     'Từ chối vì quy định cấm: 吸っては いけません.', TRUE, 'te-form'),
    ('Cấm đoán: V てはいけません', 'Ý nghĩa của ここで 写真を 撮っては いけません:', '["Ở đây cấm chụp ảnh","Ở đây được chụp ảnh","Ở đây nên chụp ảnh","Ở đây tôi muốn chụp ảnh"]', 'Ở đây cấm chụp ảnh',
     'てはいけません diễn tả quy định cấm (mạnh hơn ないでください).', FALSE, NULL),
    ('Yêu cầu đừng làm: V ないでください', 'ここで タバコを 吸わ __ ください。', '["ないで","なくて","ない","ないて"]', 'ないで',
     'V-ない + でください: 吸わないで ください.', FALSE, NULL),
    ('Yêu cầu đừng làm: V ないでください', 'Thể ない của 入ります:', '["入らない","入りない","入るない","入りません"]', '入らない',
     'Động từ nhóm 1: 入ります → 入らない (thể ない).', TRUE, 'te-form'),
    ('Yêu cầu đừng làm: V ないでください', 'A: すみません、__。 B: あ、すみません。', '["ここに 自転車を とめないで ください","ここに 自転車を とめては いけません","ここに 自転車を とめても いいですか","ここに 自転車を とめます"]', 'ここに 自転車を とめないで ください',
     'Nhờ nhẹ nhàng dùng ないで ください, khác với quy định cấm ては いけません.', FALSE, NULL)
) AS e(rule_title, question_text, options_json, correct_answer, explanation, is_common_mistake, mistake_category)
JOIN grammar_rules r ON r.title = e.rule_title
ON CONFLICT (grammar_rule_id, question_text) DO NOTHING;
