-- Only facts not recoverable from existing account/learning records.
CREATE TABLE product_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_name VARCHAR(40) NOT NULL,
    module VARCHAR(16) NOT NULL,
    event_key UUID NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_event_pair CHECK (
        (event_name = 'auth.login.v1' AND module = 'AUTH') OR
        (event_name = 'learning.started.v1' AND module IN ('SRS', 'GRAMMAR'))
    ),
    CONSTRAINT uq_product_event_key UNIQUE (user_id, event_name, event_key)
);
-- Supports time-bounded operational funnel counts, not per-click tracking.
CREATE INDEX ix_product_event_name_time ON product_events(event_name, occurred_at);
