-- =========================================================
-- V3: Seed bảng kana — Hiragana + Katakana (46 chữ cơ bản) +
--     biến âm, âm ghép, Katakana mở rộng (tổ hợp từ mượn) và ký tự đôi (促音・長音).
--
-- ⚠️ DRAFT — file này sinh tự động từ frontend/src/features/kana/kanaData.ts.
--    Nội dung CHƯA được người biết tiếng Nhật duyệt: không promote lên production
--    trước khi review xong (docs/Internal/content-mapping-fpt-curriculum.md).
--
-- Quy tắc mapping nhóm:
--   GOJUON / DAKUTEN / HANDAKUTEN / YOON  — giữ nguyên
--   EXTENDED_KATAKANA                     — tổ hợp âm cho từ mượn (ファ / ウィ / ツォ ...)
--   DOUBLE_KATAKANA -> SOKUON (ッ) hoặc CHOON (ー) theo đúng schema V1
--
-- は / へ / を KHÔNG tách thành ký tự riêng: chỉ gắn cờ is_particle_exception.
-- =========================================================

-- Ràng buộc duy nhất để seed chạy lại nhiều lần không tạo dữ liệu trùng.
CREATE UNIQUE INDEX IF NOT EXISTS uq_kana_character_type ON kana (character, kana_type);

INSERT INTO kana (character, romaji, kana_type, kana_group, is_particle_exception, notes)
VALUES
  ('あ', 'a', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('い', 'i', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('う', 'u', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('え', 'e', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('お', 'o', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('か', 'ka', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('き', 'ki', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('く', 'ku', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('け', 'ke', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('こ', 'ko', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('さ', 'sa', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('し', 'shi', 'HIRAGANA', 'GOJUON', FALSE, 'Đọc "shi", không đọc "si".'),
  ('す', 'su', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('せ', 'se', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('そ', 'so', 'HIRAGANA', 'GOJUON', FALSE, 'Nhóm dễ nhầm し / つ / そ / ん — chú ý nét ngang trên cùng.'),
  ('た', 'ta', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ち', 'chi', 'HIRAGANA', 'GOJUON', FALSE, 'Đọc "chi", không đọc "ti".'),
  ('つ', 'tsu', 'HIRAGANA', 'GOJUON', FALSE, 'Đọc "tsu". Nhóm dễ nhầm し / つ / そ / ん — chú ý hướng nét cong.'),
  ('て', 'te', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('と', 'to', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('な', 'na', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('に', 'ni', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ぬ', 'nu', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ね', 'ne', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('の', 'no', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('は', 'ha', 'HIRAGANA', 'GOJUON', TRUE, 'Viết là は nhưng khi làm trợ từ thì đọc "wa". Là trợ từ đứng sau chủ đề câu. VD: わたし は がくせい です (watashi wa gakusei desu) = Tôi là học sinh.'),
  ('ひ', 'hi', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ふ', 'fu', 'HIRAGANA', 'GOJUON', FALSE, 'Đọc "fu" — phát âm nhẹ, nằm giữa "hu" và "fu".'),
  ('へ', 'he', 'HIRAGANA', 'GOJUON', TRUE, 'Viết là へ nhưng khi làm trợ từ chỉ hướng thì đọc "e". VD: とうきょう へ いきます (Tōkyō e ikimasu) = Tôi đi đến Tokyo.'),
  ('ほ', 'ho', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ま', 'ma', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('み', 'mi', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('む', 'mu', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('め', 'me', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('も', 'mo', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('や', 'ya', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ゆ', 'yu', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('よ', 'yo', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ら', 'ra', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('り', 'ri', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('る', 'ru', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('れ', 're', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('ろ', 'ro', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('わ', 'wa', 'HIRAGANA', 'GOJUON', FALSE, NULL),
  ('を', 'wo', 'HIRAGANA', 'GOJUON', TRUE, 'Chỉ dùng làm trợ từ (đánh dấu tân ngữ), đọc "o" — không dùng trong từ thông thường. VD: ごはん を たべます (gohan o tabemasu) = Tôi ăn cơm.'),
  ('ん', 'n', 'HIRAGANA', 'GOJUON', FALSE, 'Âm mũi "n" đứng một mình, không ghép nguyên âm.'),
  ('が', 'ga', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぎ', 'gi', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぐ', 'gu', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('げ', 'ge', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ご', 'go', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ざ', 'za', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('じ', 'ji', 'HIRAGANA', 'DAKUTEN', FALSE, 'Đọc "ji".'),
  ('ず', 'zu', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぜ', 'ze', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぞ', 'zo', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('だ', 'da', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぢ', 'ji (di)', 'HIRAGANA', 'DAKUTEN', FALSE, 'Đọc giống じ. Chỉ dùng khi ghép (VD: ちぢむ, はなぢ) — gõ "di" hoặc "dji".'),
  ('づ', 'zu (du)', 'HIRAGANA', 'DAKUTEN', FALSE, 'Đọc giống ず. Chỉ dùng trong vài từ (VD: つづく, みかづき).'),
  ('で', 'de', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ど', 'do', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ば', 'ba', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('び', 'bi', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぶ', 'bu', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('べ', 'be', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぼ', 'bo', 'HIRAGANA', 'DAKUTEN', FALSE, NULL),
  ('ぱ', 'pa', 'HIRAGANA', 'HANDAKUTEN', FALSE, NULL),
  ('ぴ', 'pi', 'HIRAGANA', 'HANDAKUTEN', FALSE, NULL),
  ('ぷ', 'pu', 'HIRAGANA', 'HANDAKUTEN', FALSE, NULL),
  ('ぺ', 'pe', 'HIRAGANA', 'HANDAKUTEN', FALSE, NULL),
  ('ぽ', 'po', 'HIRAGANA', 'HANDAKUTEN', FALSE, NULL),
  ('きゃ', 'kya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('きゅ', 'kyu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('きょ', 'kyo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('しゃ', 'sha', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('しゅ', 'shu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('しょ', 'sho', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ちゃ', 'cha', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ちゅ', 'chu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ちょ', 'cho', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('にゃ', 'nya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('にゅ', 'nyu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('にょ', 'nyo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ひゃ', 'hya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ひゅ', 'hyu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ひょ', 'hyo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('みゃ', 'mya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('みゅ', 'myu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('みょ', 'myo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('りゃ', 'rya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('りゅ', 'ryu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('りょ', 'ryo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぎゃ', 'gya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぎゅ', 'gyu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぎょ', 'gyo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('じゃ', 'ja', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('じゅ', 'ju', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('じょ', 'jo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('びゃ', 'bya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('びゅ', 'byu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('びょ', 'byo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぴゃ', 'pya', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぴゅ', 'pyu', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ぴょ', 'pyo', 'HIRAGANA', 'YOON', FALSE, NULL),
  ('ア', 'a', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('イ', 'i', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ウ', 'u', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('エ', 'e', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('オ', 'o', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('カ', 'ka', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('キ', 'ki', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ク', 'ku', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ケ', 'ke', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('コ', 'ko', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('サ', 'sa', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('シ', 'shi', 'KATAKANA', 'GOJUON', FALSE, 'Nhóm dễ nhầm シ / ツ / ソ / ン. シ có 2 nét nhỏ hướng vào trong, nét dài cong từ dưới lên.'),
  ('ス', 'su', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('セ', 'se', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ソ', 'so', 'KATAKANA', 'GOJUON', FALSE, 'Nhóm dễ nhầm ソ / ン. ソ nét dài kéo từ trên trái xuống dưới phải.'),
  ('タ', 'ta', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('チ', 'chi', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ツ', 'tsu', 'KATAKANA', 'GOJUON', FALSE, 'Nhóm dễ nhầm シ / ツ / ソ / ン. ツ có 2 nét nhỏ hướng xuống dưới, nét dài cong từ trên xuống.'),
  ('テ', 'te', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ト', 'to', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ナ', 'na', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ニ', 'ni', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ヌ', 'nu', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ネ', 'ne', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ノ', 'no', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ハ', 'ha', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ヒ', 'hi', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('フ', 'fu', 'KATAKANA', 'GOJUON', FALSE, 'Đọc "fu" — âm môi nhẹ, khác với "hu" tiếng Việt.'),
  ('ヘ', 'he', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ホ', 'ho', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('マ', 'ma', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ミ', 'mi', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ム', 'mu', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('メ', 'me', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('モ', 'mo', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ヤ', 'ya', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ユ', 'yu', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ヨ', 'yo', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ラ', 'ra', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('リ', 'ri', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ル', 'ru', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('レ', 're', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ロ', 'ro', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ワ', 'wa', 'KATAKANA', 'GOJUON', FALSE, NULL),
  ('ヲ', 'wo', 'KATAKANA', 'GOJUON', FALSE, 'Gần như không dùng trong từ mượn hiện đại; chỉ gặp ở văn bản cổ hoặc tên riêng.'),
  ('ン', 'n', 'KATAKANA', 'GOJUON', FALSE, 'Nhóm dễ nhầm ソ / ン. ン nét dài kéo từ dưới trái lên trên phải.'),
  ('ガ', 'ga', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ギ', 'gi', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('グ', 'gu', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ゲ', 'ge', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ゴ', 'go', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ザ', 'za', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ジ', 'ji', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ズ', 'zu', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ゼ', 'ze', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ゾ', 'zo', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ダ', 'da', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ヂ', 'ji (di)', 'KATAKANA', 'DAKUTEN', FALSE, 'Đọc giống ジ, hầu như không dùng ở katakana.'),
  ('ヅ', 'zu (du)', 'KATAKANA', 'DAKUTEN', FALSE, 'Đọc giống ズ, hầu như không dùng ở katakana.'),
  ('デ', 'de', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ド', 'do', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('バ', 'ba', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ビ', 'bi', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ブ', 'bu', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ベ', 'be', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('ボ', 'bo', 'KATAKANA', 'DAKUTEN', FALSE, NULL),
  ('パ', 'pa', 'KATAKANA', 'HANDAKUTEN', FALSE, NULL),
  ('ピ', 'pi', 'KATAKANA', 'HANDAKUTEN', FALSE, NULL),
  ('プ', 'pu', 'KATAKANA', 'HANDAKUTEN', FALSE, NULL),
  ('ペ', 'pe', 'KATAKANA', 'HANDAKUTEN', FALSE, NULL),
  ('ポ', 'po', 'KATAKANA', 'HANDAKUTEN', FALSE, NULL),
  ('キャ', 'kya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('キュ', 'kyu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('キョ', 'kyo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('シャ', 'sha', 'KATAKANA', 'YOON', FALSE, NULL),
  ('シュ', 'shu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ショ', 'sho', 'KATAKANA', 'YOON', FALSE, NULL),
  ('チャ', 'cha', 'KATAKANA', 'YOON', FALSE, NULL),
  ('チュ', 'chu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('チョ', 'cho', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ニャ', 'nya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ニュ', 'nyu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ニョ', 'nyo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ヒャ', 'hya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ヒュ', 'hyu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ヒョ', 'hyo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ミャ', 'mya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ミュ', 'myu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ミョ', 'myo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('リャ', 'rya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('リュ', 'ryu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('リョ', 'ryo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ギャ', 'gya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ギュ', 'gyu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ギョ', 'gyo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ジャ', 'ja', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ジュ', 'ju', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ジョ', 'jo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ビャ', 'bya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ビュ', 'byu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ビョ', 'byo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ピャ', 'pya', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ピュ', 'pyu', 'KATAKANA', 'YOON', FALSE, NULL),
  ('ピョ', 'pyo', 'KATAKANA', 'YOON', FALSE, NULL),
  ('イェ', 'ye', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "ye" trong từ ngoại lai (VD: イェール = Yale).'),
  ('ウィ', 'wi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "wi". Tiếng Nhật không có âm wi riêng nên ghép ウ + ィ nhỏ. VD: ウィンドウ (windō) = Cửa sổ (máy tính); ウィスキー (wisukī) = Rượu whisky'),
  ('ウェ', 'we', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "we". VD: ウェブ (webu) = Web; ウェイト (weito) = Tạ / cân nặng'),
  ('ウォ', 'wo', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "wo". VD: ウォッチ (wotchi) = Đồng hồ đeo tay; ウォーター (wōtā) = Nước'),
  ('ファ', 'fa', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "fa": フ + ァ nhỏ. VD: ファン (fan) = Người hâm mộ; ソファ (sofa) = Ghế sofa'),
  ('フィ', 'fi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "fi": フ + ィ nhỏ. VD: フィルム (firumu) = Phim (ảnh)'),
  ('フェ', 'fe', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "fe": フ + ェ nhỏ. VD: カフェ (kafe) = Quán cà phê; フェス (fesu) = Lễ hội âm nhạc'),
  ('フォ', 'fo', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "fo": フ + ォ nhỏ. VD: フォーク (fōku) = Cái nĩa; ソフト (sofuto) = Phần mềm / mềm'),
  ('フュ', 'fyu', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "fyu", ít gặp. VD: フュージョン (fyūjon) = Sự kết hợp (fusion)'),
  ('ヴァ', 'va', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "va". ヴ là chữ katakana dành riêng cho âm "v". VD: ヴァイオリン (vaiorin) = Đàn violin'),
  ('ヴィ', 'vi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "vi". VD: ヴィザ (viza) = Thị thực (visa)'),
  ('ヴ', 'vu', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "vu". Nhiều người Nhật vẫn đọc thành "bu" — dạng viết khác là ブ.'),
  ('ヴェ', 've', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "ve".'),
  ('ヴォ', 'vo', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "vo". VD: ヴォーカル (vōkaru) = Giọng ca chính'),
  ('シェ', 'she', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "she" — khác セ (se). VD: シェア (shea) = Chia sẻ / thị phần'),
  ('ジェ', 'je', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "je" — khác ゼ (ze). VD: ジェット (jetto) = Máy bay phản lực'),
  ('チェ', 'che', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "che" — khác セ (se). VD: チェック (chekku) = Kiểm tra'),
  ('ティ', 'ti', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "ti" — khác チ (chi). VD: パーティー (pātī) = Bữa tiệc'),
  ('ディ', 'di', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "di" — khác ジ (ji). VD: ディナー (dinā) = Bữa tối'),
  ('テュ', 'tyu', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tyu", ít gặp.'),
  ('デュ', 'dyu', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "dyu", ít gặp.'),
  ('トゥ', 'tu', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tu" — khác ツ (tsu). VD: フット (futto) = Bóng đá (foot)'),
  ('ドゥ', 'du', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "du" — khác ズ (zu).'),
  ('ツァ', 'tsa', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tsa". VD: モッツァレラ (mottsuarella) = Phô mai mozzarella'),
  ('ツィ', 'tsi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tsi", ít gặp.'),
  ('ツェ', 'tse', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tse", ít gặp.'),
  ('ツォ', 'tso', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "tso" — thường gặp khi phiên âm tiếng Ý. VD: カルツォーネ (karutsōne) = Bánh calzone'),
  ('スィ', 'si', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "si" — phần lớn trường hợp tiếng Nhật vẫn viết thành シ.'),
  ('ズィ', 'zi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "zi" — phần lớn trường hợp tiếng Nhật vẫn viết thành ジ.'),
  ('クァ', 'kwa', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "kwa", ít gặp.'),
  ('クィ', 'kwi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "kwi", ít gặp.'),
  ('クェ', 'kwe', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "kwe", ít gặp.'),
  ('クォ', 'kwo', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "kwo", ít gặp. VD: クォーター (kwōtā) = Một phần tư'),
  ('グァ', 'gwa', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "gwa", ít gặp.'),
  ('グィ', 'gwi', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "gwi", ít gặp.'),
  ('グェ', 'gwe', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "gwe", ít gặp.'),
  ('グォ', 'gwo', 'KATAKANA', 'EXTENDED_KATAKANA', FALSE, 'Phiên âm "gwo", ít gặp.'),
  ('ッ', 'gấp đôi phụ âm', 'KATAKANA', 'SOKUON', FALSE, '促音 (sokuon): viết nhỏ hơn ツ, KHÔNG đọc thành "tsu" mà gấp đôi phụ âm đứng sau (ベッド = be-ddo). VD: ベッド (beddo) = Cái giường; カップ (kappu) = Cái cốc; サッカー (sakkā) = Bóng đá; ペット (petto) = Thú cưng'),
  ('ー', 'kéo dài nguyên âm', 'KATAKANA', 'CHOON', FALSE, '長音 (chōon): kéo dài nguyên âm của ký tự đứng trước (コーヒー = koohii). Hiragana không dùng dấu này. VD: コーヒー (kōhī) = Cà phê; ケーキ (kēki) = Bánh ngọt; タクシー (takushī) = Taxi; スーパー (sūpā) = Siêu thị')
ON CONFLICT (character, kana_type) DO NOTHING;
