-- =========================================================
-- V6: Seed bảng radicals (bộ thủ)
--
-- Phạm vi: các bộ thủ xuất hiện trong kanji bài JPD113/JPD123 (Phase 3) + một số bộ thủ
-- thông dụng hay gặp. KHÔNG seed toàn bộ 214 bộ thủ ở bước này (tránh dữ liệu không dùng tới).
--
-- Nguồn cách đọc tên bộ: danh pháp bộ thủ tiếng Nhật thông dụng (kyōiku/jōyō reference).
-- Nghĩa Hán Việt do người soạn nội dung viết lại, không copy nguyên văn từ tài liệu nào.
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS uq_radical_character ON radicals (radical);

INSERT INTO radicals (radical, stroke_count, name, meaning) VALUES
    ('一', 1, 'ichi', 'một (nét ngang)'),
    ('丨', 1, 'bou', 'nét sổ thẳng'),
    ('亅', 1, 'hanebou', 'nét móc'),
    ('亠', 2, 'nabebuta', 'nắp, nét đầu'),
    ('人', 2, 'hito', 'người'),
    ('儿', 2, 'hitoashi', 'chân người'),
    ('入', 2, 'iru', 'vào'),
    ('冂', 2, 'maki', 'khuôn bao ngoài'),
    ('刀', 2, 'katana', 'dao, gươm'),
    ('力', 2, 'chikara', 'sức mạnh'),
    ('十', 2, 'juu', 'mười (nét ngang dọc)'),
    ('凵', 2, 'ukebako', 'hộp mở miệng'),
    ('口', 3, 'kuchi', 'miệng, cái hộp'),
    ('囗', 3, 'kuni', 'vây quanh, thành bao'),
    ('土', 3, 'tsuchi', 'đất'),
    ('士', 3, 'samurai', 'kẻ sĩ, người học'),
    ('夕', 3, 'yuu', 'buổi tối'),
    ('大', 3, 'dai', 'to, lớn'),
    ('女', 3, 'onna', 'phụ nữ'),
    ('子', 3, 'ko', 'trẻ con'),
    ('宀', 3, 'ukanmuri', 'mái nhà'),
    ('寸', 3, 'sun', 'tấc (đơn vị đo)'),
    ('小', 3, 'shou', 'nhỏ'),
    ('山', 3, 'yama', 'núi'),
    ('巾', 3, 'haba', 'khăn, vải'),
    ('广', 3, 'madare', 'mái che'),
    ('廴', 3, 'ennyou', 'bước dài'),
    ('己', 3, 'onore', 'bản thân, kỷ'),
    ('艹', 3, 'kusakanmuri', 'cỏ'),
    ('心', 4, 'kokoro', 'trái tim, tấm lòng'),
    ('手', 4, 'te', 'tay'),
    ('斤', 4, 'ono', 'cái rìu'),
    ('方', 4, 'kata', 'phương hướng'),
    ('日', 4, 'hi', 'mặt trời, ngày'),
    ('月', 4, 'tsuki', 'mặt trăng, tháng'),
    ('木', 4, 'ki', 'cây, gỗ'),
    ('欠', 4, 'akubi', 'thiếu, ngáp'),
    ('水', 4, 'mizu', 'nước'),
    ('火', 4, 'hi', 'lửa'),
    ('犬', 4, 'inu', 'con chó'),
    ('牛', 4, 'ushi', 'con bò'),
    ('玉', 5, 'tama', 'viên ngọc'),
    ('生', 5, 'umareru', 'sinh, sống'),
    ('田', 5, 'ta', 'ruộng'),
    ('白', 5, 'shiro', 'màu trắng'),
    ('皿', 5, 'sara', 'cái đĩa'),
    ('目', 5, 'me', 'con mắt'),
    ('禾', 5, 'nogihen', 'cây lúa'),
    ('立', 5, 'tatsu', 'đứng, lập'),
    ('竹', 6, 'take', 'cây tre'),
    ('米', 6, 'kome', 'gạo'),
    ('糸', 6, 'ito', 'sợi tơ'),
    ('耳', 6, 'mimi', 'tai'),
    ('行', 6, 'gyou', 'đi, hàng'),
    ('走', 7, 'sou', 'chạy'),
    ('谷', 7, 'tani', 'thung lũng'),
    ('貝', 7, 'kai', 'vỏ sò (tiền cổ)'),
    ('車', 7, 'kuruma', 'xe'),
    ('言', 7, 'gen', 'lời nói'),
    ('阝', 7, 'oozato', 'gò đất / thành phố'),
    ('金', 8, 'kane', 'kim loại, vàng'),
    ('門', 8, 'mon', 'cổng lớn'),
    ('雨', 8, 'ame', 'mưa'),
    ('食', 9, 'shoku', 'ăn, đồ ăn'),
    ('音', 9, 'oto', 'âm thanh'),
    ('飛', 9, 'tobu', 'bay'),
    ('高', 10, 'takai', 'cao'),
    ('斗', 4, 'tomasu', 'cái đấu (đơn vị đo)'),
    ('气', 4, 'kigamae', 'hơi nước, khí'),
    ('夂', 3, 'fuyugashira', 'đi chậm, mùa đông')
ON CONFLICT (radical) DO NOTHING;
