-- =========================================================
-- V9: Seed bảng grammar_exercises (Phase 4)
--
-- Bộ khởi điểm: 2 câu cho mỗi điểm ngữ pháp (đủ để UI hoạt động end-to-end).
-- Nhóm bẫy thường gặp (は/へ/を, số đếm biến âm, tính từ, so sánh, thể て) được gắn
-- is_common_mistake = TRUE + mistake_category để lọc riêng ở Trạm Trợ từ.
--
-- ⚠️ TODO sau review nội dung: bổ sung lên tối thiểu 5 câu/điểm và 10+ câu cho nhóm bẫy
--    (kế hoạch bổ sung nội dung sau review). Nội dung do người soạn tự viết, chưa copy nguồn.
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS uq_grammar_exercise_rule_question ON grammar_exercises (grammar_rule_id, question_text);

INSERT INTO grammar_exercises (grammar_rule_id, question_text, options_json, correct_answer, explanation, is_common_mistake, mistake_category)
SELECT r.id, e.question_text, e.options_json, e.correct_answer, e.explanation, e.is_common_mistake, e.mistake_category
FROM (VALUES
    -- ===== JPD113 — Bài 1 =====
    ('N1 は N2 です', 'わたし __ がくせい です。', '["は","を","に","で"]', 'は',
     'は đánh dấu chủ đề của câu (ở đây là "わたし"). Chú ý: は khi làm trợ từ đọc là "wa".', TRUE, 'particle-ha'),
    ('N1 は N2 です', 'たなかさん __ せんせい です。', '["の","は","か","を"]', 'は',
     'Câu khẳng định N1 は N2 です: は đứng sau chủ thể được nói tới.', FALSE, NULL),
    ('N1 は N2 じゃありません', 'わたし は せんせい __ ありません。', '["では","です","ます","を"]', 'では',
     'Phủ định lịch sự: ではありません (khẩu ngữ: じゃありません).', FALSE, NULL),
    ('N1 は N2 じゃありません', 'A: がくせい ですか。 B: いいえ、がくせい __。', '["じゃありません","です","でした","ですか"]', 'じゃありません',
     'Trả lời phủ định cho câu hỏi danh từ dùng じゃありません / ではありません.', TRUE, 'polite-negative'),
    ('N1 は N2 ですか', 'あなた は ベトナム人 __。', '["ですか","です","かです","でした"]', 'ですか',
     'Câu hỏi thêm か ở cuối, không đổi trật tự từ.', FALSE, NULL),
    ('N1 は N2 ですか', 'A: あの 人は がくせいですか。 B: はい、__。', '["そうです","ちがいます","ですか","です"]', 'そうです',
     'Trả lời khẳng định: はい、そうです. Nếu phủ định: いいえ、ちがいます.', FALSE, NULL),
    ('N も', 'A: たなかさん は がくせいですか。 B: はい。 わたし __ がくせいです。', '["も","を","に","へ"]', 'も',
     'も thay cho は khi muốn nói "cũng": わたし も がくせいです.', FALSE, NULL),
    ('N も', 'リンさん は ベトナム人です。 たなかさん __ ベトナム人です。', '["も","の","を","で"]', 'も',
     'Cùng thuộc tính với người đã nhắc trước đó → dùng も.', FALSE, NULL),
    ('N1 の N2', 'これ は わたし __ 本 です。', '["の","は","を","と"]', 'の',
     'の nối hai danh từ: わたし の 本 = sách của tôi.', FALSE, NULL),
    ('N1 の N2', 'FPT __ がくせい です。', '["の","は","に","で"]', 'の',
     'の cũng dùng để chỉ nơi xuất xứ/thuộc về: FPT の がくせい.', FALSE, NULL),
    -- ===== JPD113 — Bài 2 =====
    ('これ / それ / あれ は N です', '(cầm vật gần mình) __ は わたし の かばんです。', '["これ","それ","あれ","どれ"]', 'これ',
     'これ = vật ở gần người nói. それ gần người nghe, あれ xa cả hai.', FALSE, NULL),
    ('これ / それ / あれ は N です', '(vật ở xa cả hai người) __ は なんですか。', '["あれ","これ","それ","この"]', 'あれ',
     'あれ dùng cho vật ở xa cả người nói và người nghe. この phải đi kèm danh từ.', FALSE, NULL),
    ('N は どこですか', 'トイレ __ どこですか。', '["は","が","を","に"]', 'は',
     'Mẫu hỏi vị trí: N は どこですか.', FALSE, NULL),
    ('N は どこですか', 'しょくどう は __ ですか。', '["どこ","だれ","なに","いつ"]', 'どこ',
     'どこ là nghi vấn từ chỉ nơi chốn, dùng cho câu hỏi "ở đâu".', FALSE, NULL),
    ('N が あります / います', 'つくえ の 上 に 本 __ あります。', '["が","は","を","で"]', 'が',
     'Câu tồn tại: <nơi> に <vật> が あります. Chủ thể tồn tại đánh dấu bằng が (không dùng は).', TRUE, 'particle-ga'),
    ('N が あります / います', 'こうえん に 子ども __ います。', '["が","を","に","へ"]', 'が',
     'Người/động vật dùng います: こうえん に 子ども が います.', TRUE, 'particle-ga'),
    ('Vị trí tương đối: 上 / 下 / 前 / 後ろ / 隣 / 中', '本 は つくえ __ 上 に あります。', '["の","は","に","が"]', 'の',
     'Cấu trúc: N1 の 上/下/前/後ろ/隣/中 に N2 が あります.', FALSE, NULL),
    ('Vị trí tương đối: 上 / 下 / 前 / 後ろ / 隣 / 中', 'ねこ は いす __ 下 に います。', '["の","を","へ","と"]', 'の',
     'の nối vật mốc với từ chỉ vị trí: いす の 下 = dưới ghế.', FALSE, NULL),
    ('N は N の 中 です', 'かぎ は はこ __ 中 です。', '["の","に","は","も"]', 'の',
     'Xác định vị trí: N1 は N2 の 中 です (N1 ở trong N2).', FALSE, NULL),
    ('N は N の 中 です', 'かばん は どこですか。 → かばん は へや __ あります。', '["に","を","へ","と"]', 'に',
     'Có thể diễn đạt bằng に あります thay cho の 中 です: へや に あります.', FALSE, NULL),
    -- ===== JPD113 — Bài 3 =====
    ('いくらですか', 'この かばん は __ ですか。', '["いくら","どこ","なに","いつ"]', 'いくら',
     'いくら là nghi vấn từ hỏi giá tiền.', FALSE, NULL),
    ('いくらですか', '(giá 500 yên) ごひゃく __ です。', '["円","月","日","時"]', '円',
     'Đơn vị tiền Nhật là 円 (えん): ごひゃくえん = 500 yên.', FALSE, NULL),
    ('N を ください', 'コーヒー __ ください。', '["を","は","が","に"]', 'を',
     'を đánh dấu tân ngữ (vật được yêu cầu). Chú ý: を làm trợ từ đọc là "o", không đọc "wo".', TRUE, 'particle-wo'),
    ('N を ください', 'この 本 __ ください。', '["を","へ","と","で"]', 'を',
     'Mẫu mua/yêu cầu: N を ください.', TRUE, 'particle-wo'),
    ('Giờ và phút: ～時 ～分', '４時 = ?', '["よじ","しじ","よんじ","しちじ"]', 'よじ',
     'Bẫy biến âm giờ: 4時 = よじ (không phải よんじ), 7時 = しちじ, 9時 = くじ.', TRUE, 'counter-time'),
    ('Giờ và phút: ～時 ～分', '７時 = ?', '["しちじ","ななじ","ひちじ","しじ"]', 'しちじ',
     '7時 đọc là しちじ (không dùng ななじ cho giờ).', TRUE, 'counter-time'),
    ('Ngày tháng và thứ: ～月 ～日 ・～曜日', '１４日 = ?', '["じゅうよっか","じゅうよんにち","じゅうしにち","じゅうよんか"]', 'じゅうよっか',
     'Bẫy biến âm ngày: 14日 = じゅうよっか (đổi hẳn cách đọc), 20日 = はつか, 24日 = にじゅうよっか.', TRUE, 'counter-date'),
    ('Ngày tháng và thứ: ～月 ～日 ・～曜日', '２０日 = ?', '["はつか","にじゅうにち","にじゅっか","はつひ"]', 'はつか',
     '20日 là ngoại lệ đặc biệt: はつか. Các ngày 17, 19, 27, 29 chỉ biến âm phần cuối: じゅうしちにち, じゅうくにち, にじゅうしちにち, にじゅうくにち.', TRUE, 'counter-date'),
    ('Chia động từ: V ます / V ません', 'まいにち 日本語 を べんきょう __。', '["します","しません","しました","する"]', 'します',
     'Thể lịch sự hiện tại khẳng định: V-ます (べんきょうします).', FALSE, NULL),
    ('Chia động từ: V ます / V ません', 'A: あした 学校へ 行きますか。 B: いいえ、__。', '["行きません","行きます","行きました","行く"]', '行きません',
     'Phủ định thể lịch sự: V-ません (行きません).', FALSE, NULL),
    ('N へ 行きます', 'あした 日本 __ 行きます。', '["へ","を","で","と"]', 'へ',
     'へ (hoặc に) đánh dấu hướng/đích đến. Chú ý: へ làm trợ từ đọc là "e", không đọc "he".', TRUE, 'particle-he'),
    ('N へ 行きます', 'うち __ 帰ります。', '["へ","を","が","も"]', 'へ',
     '帰ります là động từ di chuyển về, cũng dùng へ/に: うち へ 帰ります.', TRUE, 'particle-he'),
    ('N で 行きます', '電車 __ 会社へ 行きます。', '["で","に","へ","を"]', 'で',
     'で đánh dấu phương tiện: 電車 で 行きます (đi bằng tàu điện).', FALSE, NULL),
    ('N で 行きます', '(đi bộ) 学校へ __ 行きます。', '["あるいて","で","に","へ"]', 'あるいて',
     'Đi bộ không dùng で mà dùng あるいて 行きます.', TRUE, 'transport'),
    -- ===== JPD123 — Bài 4 =====
    ('Tính từ đuôi い và な', 'きれい __ 花 です。', '["な","い","の","で"]', 'な',
     'きれい là tính từ nhóm な nên khi bổ nghĩa danh từ phải thêm な.', TRUE, 'adjective-na'),
    ('Tính từ đuôi い và な', 'たかい __ 山 です。', '["い","な","の","に"]', 'い',
     'たかい thuộc nhóm い, giữ nguyên い khi đứng trước danh từ.', FALSE, NULL),
    ('Phủ định tính từ い', 'たかい → phủ định:', '["たかくないです","たかいじゃないです","たかくありませんです","たかではないです"]', 'たかくないです',
     'Tính từ い: bỏ い rồi thêm くないです.', TRUE, 'adjective-i'),
    ('Phủ định tính từ い', 'いい → phủ định:', '["よくないです","いくないです","いじゃないです","いいくないです"]', 'よくないです',
     'Ngoại lệ bắt buộc nhớ: いい → よくないです (không phải いくない).', TRUE, 'adjective-i'),
    ('Phủ định tính từ な', 'きれい → phủ định:', '["きれいじゃないです","きれくないです","きれいないです","きれではないです"]', 'きれいじゃないです',
     'Tính từ な: giữ nguyên từ rồi thêm じゃないです.', TRUE, 'adjective-na'),
    ('Phủ định tính từ な', 'しずか → phủ định:', '["しずかじゃないです","しずかくないです","しずかないです","しずじゃないです"]', 'しずかじゃないです',
     'しずか là tính từ な → しずかじゃないです (không thêm く).', TRUE, 'adjective-na'),
    ('N が ほしいです', 'あたらしい 車 __ ほしいです。', '["が","を","は","に"]', 'が',
     'Đối tượng mong muốn đánh dấu bằng が: N が ほしいです.', FALSE, NULL),
    ('N が ほしいです', 'A: なに __ ほしいですか。', '["が","を","で","と"]', 'が',
     'Câu hỏi cũng dùng が: なに が ほしいですか.', FALSE, NULL),
    ('V たいです', '日本へ __ です。', '["行きたい","行たい","行くたい","行きほしい"]', '行きたい',
     'V-たい: bỏ ます của 行きます → 行き + たいです.', FALSE, NULL),
    ('V たいです', 'Phủ định của 行きたいです:', '["行きたくないです","行きたくありませんです","行きたいじゃないです","行くないです"]', '行きたくないです',
     'V-たい chia như tính từ い: 行きたくないです.', TRUE, 'verb-tai'),
    -- ===== JPD123 — Bài 5 =====
    ('Mục đích chuyến đi: V に 行きます', '日本へ 映画を __ 行きます。', '["見に","見て","見る","見たい"]', '見に',
     'Mục đích: V(ます形 bỏ ます) + に 行きます → 見に 行きます.', FALSE, NULL),
    ('Mục đích chuyến đi: V に 行きます', 'デパートへ かばんを __ 行きます。', '["買いに","買って","買う","買いたい"]', '買いに',
     '買います → 買い + に: 買いに 行きます.', FALSE, NULL),
    ('N と V ます (làm cùng ai)', '友達 __ 旅行します。', '["と","を","に","で"]', 'と',
     'と đánh dấu người cùng tham gia hành động.', FALSE, NULL),
    ('N と V ます (làm cùng ai)', '(đi một mình) 一人 __ 行きます。', '["で","と","に","へ"]', 'で',
     'Đi một mình dùng 一人で, không dùng と.', TRUE, 'particle-de'),
    ('Thời gian: いつ / ～から ～まで', '__ 日本へ 行きますか。', '["いつ","どこ","なに","だれ"]', 'いつ',
     'いつ hỏi thời điểm và không đi kèm に.', FALSE, NULL),
    ('Thời gian: いつ / ～から ～まで', '９時 __ ５時まで 働きます。', '["から","まで","に","で"]', 'から',
     '～から ～まで = từ ～ đến ～.', FALSE, NULL),
    -- ===== JPD123 — Bài 6 =====
    ('So sánh hơn: A と B と どちらが', 'A: 夏 と 冬 と __ が 好きですか。', '["どちら","どれ","なに","いつ"]', 'どちら',
     'So sánh hai đối tượng dùng どちら.', FALSE, NULL),
    ('So sánh hơn: A と B と どちらが', '夏 の __ が 好きです。', '["ほう","より","まで","から"]', 'ほう',
     'A の ほうが B より ～です: chọn A.', FALSE, NULL),
    ('So sánh nhất: 一番', '日本 __ 一番 高い 山 は 富士山です。', '["で","に","の","を"]', 'で',
     'Phạm vi so sánh dùng で: 日本 で 一番 ～.', TRUE, 'comparison'),
    ('So sánh nhất: 一番', '一年 __ 中 で ２月 が 一番 寒いです。', '["の","で","に","は"]', 'の',
     '一年 の 中 で = trong cả một năm, phạm vi so sánh dùng の 中 で.', TRUE, 'comparison'),
    ('Quá khứ tính từ い', 'きのう の 映画 は __ です。', '["楽しかった","楽しいかった","楽しでした","楽しだった"]', '楽しかった',
     'Tính từ い ở quá khứ: bỏ い + かったです → 楽しかったです.', TRUE, 'adjective-i'),
    ('Quá khứ tính từ い', 'テスト は __ です (phủ định quá khứ của 難しい):', '["難しくなかった","難しくないかった","難しいじゃなかった","難しいでした"]', '難しくなかった',
     'Phủ định quá khứ: 難しい → 難しくなかったです.', TRUE, 'adjective-i'),
    -- ===== JPD123 — Bài 7 =====
    ('Động từ thể て', '朝 起き __ 、顔を 洗います。', '["て","で","に","から"]', 'て',
     'Nối hai hành động bằng thể て: 起きて、～.', TRUE, 'te-form'),
    ('Động từ thể て', 'Thể て của 書く:', '["書いて","書きて","書くて","書んで"]', '書いて',
     'Động từ đuôi く (i 音) → いて: 書く → 書いて.', TRUE, 'te-form'),
    ('Xin phép: V てもいいですか', 'ここに 座っ __ いいですか。', '["ても","ては","で","て"]', 'ても',
     'Xin phép: V-て もいいですか.', FALSE, NULL),
    ('Xin phép: V てもいいですか', 'Trả lời đồng ý cho câu 写真を 撮っても いいですか:', '["はい、いいですよ","はい、いけません","いいえ、いいです","はい、だめです"]', 'はい、いいですよ',
     'Đồng ý lịch sự: いいですよ / どうぞ.', FALSE, NULL),
    ('Cấm đoán: V てはいけません', 'ここで 写真を 撮っ __ いけません。', '["ては","ても","て","では"]', 'ては',
     'Cấm đoán: V-て はいけません.', TRUE, 'te-form'),
    ('Cấm đoán: V てはいけません', 'Ý nghĩa của V てはいけません:', '["Không được làm (cấm)","Được phép làm","Muốn làm","Đã làm rồi"]', 'Không được làm (cấm)',
     'V てはいけません = không được làm (quy định cấm).', TRUE, 'te-form'),
    ('Yêu cầu đừng làm: V ないでください', 'ここで 写真を 撮ら __ ください。', '["ないで","なくて","ない","ないて"]', 'ないで',
     'V-ない + でください: 撮らないで ください.', FALSE, NULL),
    ('Yêu cầu đừng làm: V ないでください', 'Câu nào là lời nhờ nhẹ nhàng (không phải quy định cấm)?', '["撮らないでください","撮ってはいけません","撮ってもいいですか","撮ります"]', '撮らないでください',
     'V ないでください là lời nhờ, còn V てはいけません là quy định cấm.', TRUE, 'te-form')
) AS e(rule_title, question_text, options_json, correct_answer, explanation, is_common_mistake, mistake_category)
JOIN grammar_rules r ON r.title = e.rule_title
ON CONFLICT (grammar_rule_id, question_text) DO NOTHING;
